### ISSUE TITLE
Base API has changed

### ISSUE THREAD

**Issue by fnsign** [kodymallory/MMM-withings#3]
For I few days now the graphs were not displayed any more. I found out that the base API has changed and health.nokia.com is not valid anymore. I fixed it by changing following line in node-helper.js:
Change
self.baseApi = 'account.health.nokia.com';
to
self.baseApi = 'account.withings.com';

Further, to retrieve the token you must use following URL accordingly:
https://account.withings.com/oauth2_user/authorize2?response_type=code&redirect_uri=https://example.com&scope=user.info,user.metrics,user.activity&state=1&client_id=<your_client_id>

Could you please update the Readme.md and the node-helper.js?

Thanks in advance!

**Comment by bricoman2016** [comment]
Hi 

> Trong vài ngày nay, đồ thị không được hiển thị nữa. Tôi phát hiện ra rằng API cơ sở đã thay đổi và Health.nokia.com không còn hợp lệ nữa. Tôi đã sửa nó bằng cách thay đổi dòng sau trong node-helper.js:
> Thay đổi
> self.baseApi = 'account.health.nokia.com';
> to
> self.baseApi = 'account.withings.com';
> 
> Hơn nữa, để lấy token bạn phải sử dụng sau URL cho phù hợp:
> [https://account.withings.com/oauth2_user/authorize2?response_type=code&redirect_uri=https://example.com&scope=user.info,user.metrics,user.activity&state = 1 & client_id =](https://account.withings.com/oauth2_user/authorize2?response_type=code&redirect_uri=https://example.com&scope=user.info,user.metrics,user.activity&state=1&client_id=) <your_client_id>
> 
> Bạn có thể vui lòng cập nhật Readme.md và nút-helper.js không?
> 
> Cảm ơn trước!

Hi fnsign. You said it correctly, I just installed withings but after the change I still didn't get refresh_token. Can you just help me? tks

[2020-04-30 22:19:40.416] [LOG]    Whoops! There was an uncaught exception...
[2020-04-30 22:19:40.417] [ERROR]  SyntaxError: Unexpected string in JSON at position 54
    at JSON.parse (<anonymous>)
    at read (/home/pi/MagicMirror/modules/MMM-withings/node_helper.js:262:29)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
[2020-04-30 22:19:40.420] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-04-30 22:19:40.420] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[2020-04-30 22:19:40.438] [ERROR]  (node:2181) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[2020-04-30 22:19:40.439] [ERROR]  (node:2181) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

**Comment by bricoman2016** [comment]
> For I few days now the graphs were not displayed any more. I found out that the base API has changed and health.nokia.com is not valid anymore. I fixed it by changing following line in node-helper.js:
> Change
> self.baseApi = 'account.health.nokia.com';
> to
> self.baseApi = 'account.withings.com';
> 
> Further, to retrieve the token you must use following URL accordingly:
> https://account.withings.com/oauth2_user/authorize2?response_type=code&redirect_uri=https://example.com&scope=user.info,user.metrics,user.activity&state=1&client_id=<your_client_id>
> 
> Could you please update the Readme.md and the node-helper.js?
> 
> Thanks in advance!

Hi .fnsign .You said it correctly, I just installed withings but after the change I still didn't get 'refresh_token '. Can you just help me?

[2020-04-30 22:19:40.416] [LOG]    Whoops! There was an uncaught exception...
[2020-04-30 22:19:40.417] [ERROR]  SyntaxError: Unexpected string in JSON at position 54
    at JSON.parse (<anonymous>)
    at read (/home/pi/MagicMirror/modules/MMM-withings/node_helper.js:262:29)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
[2020-04-30 22:19:40.420] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-04-30 22:19:40.420] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[2020-04-30 22:19:40.438] [ERROR]  (node:2181) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[2020-04-30 22:19:40.439] [ERROR]  (node:2181) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

**Comment by kodymallory** [comment]
@fnsign I'll take a look here soon. Thanks for digging into this!

**Comment by bricoman2016** [comment]
Hi kodymallory. 
I fixed it by changing following line in node-helper.js:
Change
self.baseApi = 'account.health.nokia.com';
to
self.baseApi = 'account.withings.com';

Further, to retrieve the token you must use following URL accordingly:
https://account.withings.com/oauth2_user/authorize2?response_type=code&redirect_uri=https://example.com&scope=user.info,user.metrics,user.activity&state=1&client_id=<your_client_id>
but after the change I still didn't get 'refresh_token '. Can you just help me? pls

**Comment by kodymallory** [comment]
@fnsign I have updated the readme and node_helper.js. The health data is properly updated again for me now.

**Comment by kodymallory** [comment]
@bricoman2016 try re-running through all the steps including step 8 where you set the code received from the new URL with the token request.
